// This file is auto-generated by @hey-api/openapi-ts

export type AbpLoginResult = {
  result?: LoginResultType;
  readonly description?: string | null;
};

export type ActionApiDescriptionModel = {
  uniqueName?: string | null;
  name?: string | null;
  httpMethod?: string | null;
  url?: string | null;
  supportedVersions?: Array<string> | null;
  parametersOnMethod?: Array<MethodParameterApiDescriptionModel> | null;
  parameters?: Array<ParameterApiDescriptionModel> | null;
  returnValue?: ReturnValueApiDescriptionModel;
  allowAnonymous?: boolean | null;
  implementFrom?: string | null;
};

export type ApplicationApiDescriptionModel = {
  modules?: {
    [key: string]: ModuleApiDescriptionModel;
  } | null;
  types?: {
    [key: string]: TypeApiDescriptionModel;
  } | null;
};

export type ApplicationAuthConfigurationDto = {
  grantedPolicies?: {
    [key: string]: boolean;
  } | null;
};

export type ApplicationConfigurationDto = {
  localization?: ApplicationLocalizationConfigurationDto;
  auth?: ApplicationAuthConfigurationDto;
  setting?: ApplicationSettingConfigurationDto;
  currentUser?: CurrentUserDto;
  features?: ApplicationFeatureConfigurationDto;
  globalFeatures?: ApplicationGlobalFeatureConfigurationDto;
  multiTenancy?: MultiTenancyInfoDto;
  currentTenant?: CurrentTenantDto;
  timing?: TimingDto;
  clock?: ClockDto;
  objectExtensions?: ObjectExtensionsDto;
  extraProperties?: {
    [key: string]: unknown;
  } | null;
};

export type ApplicationFeatureConfigurationDto = {
  values?: {
    [key: string]: string | null;
  } | null;
};

export type ApplicationGlobalFeatureConfigurationDto = {
  enabledFeatures?: Array<string> | null;
};

export type ApplicationLocalizationConfigurationDto = {
  values?: {
    [key: string]: {
      [key: string]: string;
    };
  } | null;
  resources?: {
    [key: string]: ApplicationLocalizationResourceDto;
  } | null;
  languages?: Array<LanguageInfo> | null;
  currentCulture?: CurrentCultureDto;
  defaultResourceName?: string | null;
  languagesMap?: {
    [key: string]: Array<NameValue>;
  } | null;
  languageFilesMap?: {
    [key: string]: Array<NameValue>;
  } | null;
};

export type ApplicationLocalizationDto = {
  resources?: {
    [key: string]: ApplicationLocalizationResourceDto;
  } | null;
  currentCulture?: CurrentCultureDto;
};

export type ApplicationLocalizationResourceDto = {
  texts?: {
    [key: string]: string;
  } | null;
  baseResources?: Array<string> | null;
};

export type ApplicationSettingConfigurationDto = {
  values?: {
    [key: string]: string | null;
  } | null;
};

export type BookDto = {
  id?: string;
  creationTime?: string;
  creatorId?: string | null;
  lastModificationTime?: string | null;
  lastModifierId?: string | null;
  name?: string | null;
  type?: BookType;
  publishDate?: string;
  price?: number;
};

export type BookDtoPagedResultDto = {
  items?: Array<BookDto> | null;
  totalCount?: number;
};

export type BookType = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export type ChangePasswordInput = {
  currentPassword?: string | null;
  newPassword: string;
};

export type ClockDto = {
  kind?: string | null;
};

export type ControllerApiDescriptionModel = {
  controllerName?: string | null;
  controllerGroupName?: string | null;
  isRemoteService?: boolean;
  isIntegrationService?: boolean;
  apiVersion?: string | null;
  type?: string | null;
  interfaces?: Array<ControllerInterfaceApiDescriptionModel> | null;
  actions?: {
    [key: string]: ActionApiDescriptionModel;
  } | null;
};

export type ControllerInterfaceApiDescriptionModel = {
  type?: string | null;
  name?: string | null;
  methods?: Array<InterfaceMethodApiDescriptionModel> | null;
};

export type CreateUpdateBookDto = {
  name: string;
  type: BookType;
  publishDate: string;
  price: number;
};

export type CurrentCultureDto = {
  displayName?: string | null;
  englishName?: string | null;
  threeLetterIsoLanguageName?: string | null;
  twoLetterIsoLanguageName?: string | null;
  isRightToLeft?: boolean;
  cultureName?: string | null;
  name?: string | null;
  nativeName?: string | null;
  dateTimeFormat?: DateTimeFormatDto;
};

export type CurrentTenantDto = {
  id?: string | null;
  name?: string | null;
  isAvailable?: boolean;
};

export type CurrentUserDto = {
  isAuthenticated?: boolean;
  id?: string | null;
  tenantId?: string | null;
  impersonatorUserId?: string | null;
  impersonatorTenantId?: string | null;
  impersonatorUserName?: string | null;
  impersonatorTenantName?: string | null;
  userName?: string | null;
  name?: string | null;
  surName?: string | null;
  email?: string | null;
  emailVerified?: boolean;
  phoneNumber?: string | null;
  phoneNumberVerified?: boolean;
  roles?: Array<string> | null;
  sessionId?: string | null;
};

export type DateTimeFormatDto = {
  calendarAlgorithmType?: string | null;
  dateTimeFormatLong?: string | null;
  shortDatePattern?: string | null;
  fullDateTimePattern?: string | null;
  dateSeparator?: string | null;
  shortTimePattern?: string | null;
  longTimePattern?: string | null;
};

export type EmailSettingsDto = {
  smtpHost?: string | null;
  smtpPort?: number;
  smtpUserName?: string | null;
  smtpPassword?: string | null;
  smtpDomain?: string | null;
  smtpEnableSsl?: boolean;
  smtpUseDefaultCredentials?: boolean;
  defaultFromAddress?: string | null;
  defaultFromDisplayName?: string | null;
};

export type EntityExtensionDto = {
  properties?: {
    [key: string]: ExtensionPropertyDto;
  } | null;
  configuration?: {
    [key: string]: unknown;
  } | null;
};

export type ExtensionEnumDto = {
  fields?: Array<ExtensionEnumFieldDto> | null;
  localizationResource?: string | null;
};

export type ExtensionEnumFieldDto = {
  name?: string | null;
  value?: unknown;
};

export type ExtensionPropertyApiCreateDto = {
  isAvailable?: boolean;
};

export type ExtensionPropertyApiDto = {
  onGet?: ExtensionPropertyApiGetDto;
  onCreate?: ExtensionPropertyApiCreateDto;
  onUpdate?: ExtensionPropertyApiUpdateDto;
};

export type ExtensionPropertyApiGetDto = {
  isAvailable?: boolean;
};

export type ExtensionPropertyApiUpdateDto = {
  isAvailable?: boolean;
};

export type ExtensionPropertyAttributeDto = {
  typeSimple?: string | null;
  config?: {
    [key: string]: unknown;
  } | null;
};

export type ExtensionPropertyDto = {
  type?: string | null;
  typeSimple?: string | null;
  displayName?: LocalizableStringDto;
  api?: ExtensionPropertyApiDto;
  ui?: ExtensionPropertyUiDto;
  policy?: ExtensionPropertyPolicyDto;
  attributes?: Array<ExtensionPropertyAttributeDto> | null;
  configuration?: {
    [key: string]: unknown;
  } | null;
  defaultValue?: unknown;
};

export type ExtensionPropertyFeaturePolicyDto = {
  features?: Array<string> | null;
  requiresAll?: boolean;
};

export type ExtensionPropertyGlobalFeaturePolicyDto = {
  features?: Array<string> | null;
  requiresAll?: boolean;
};

export type ExtensionPropertyPermissionPolicyDto = {
  permissionNames?: Array<string> | null;
  requiresAll?: boolean;
};

export type ExtensionPropertyPolicyDto = {
  globalFeatures?: ExtensionPropertyGlobalFeaturePolicyDto;
  features?: ExtensionPropertyFeaturePolicyDto;
  permissions?: ExtensionPropertyPermissionPolicyDto;
};

export type ExtensionPropertyUiDto = {
  onTable?: ExtensionPropertyUiTableDto;
  onCreateForm?: ExtensionPropertyUiFormDto;
  onEditForm?: ExtensionPropertyUiFormDto;
  lookup?: ExtensionPropertyUiLookupDto;
};

export type ExtensionPropertyUiFormDto = {
  isVisible?: boolean;
};

export type ExtensionPropertyUiLookupDto = {
  url?: string | null;
  resultListPropertyName?: string | null;
  displayPropertyName?: string | null;
  valuePropertyName?: string | null;
  filterParamName?: string | null;
};

export type ExtensionPropertyUiTableDto = {
  isVisible?: boolean;
};

export type FeatureDto = {
  name?: string | null;
  displayName?: string | null;
  value?: string | null;
  provider?: FeatureProviderDto;
  description?: string | null;
  valueType?: IStringValueType;
  depth?: number;
  parentName?: string | null;
};

export type FeatureGroupDto = {
  name?: string | null;
  displayName?: string | null;
  features?: Array<FeatureDto> | null;
};

export type FeatureProviderDto = {
  name?: string | null;
  key?: string | null;
};

export type FindTenantResultDto = {
  success?: boolean;
  tenantId?: string | null;
  name?: string | null;
  normalizedName?: string | null;
  isActive?: boolean;
};

export type GetFeatureListResultDto = {
  groups?: Array<FeatureGroupDto> | null;
};

export type GetPermissionListResultDto = {
  entityDisplayName?: string | null;
  groups?: Array<PermissionGroupDto> | null;
};

export type IanaTimeZone = {
  timeZoneName?: string | null;
};

export type IdentityRoleCreateDto = {
  readonly extraProperties?: {
    [key: string]: unknown;
  } | null;
  name: string;
  isDefault?: boolean;
  isPublic?: boolean;
};

export type IdentityRoleDto = {
  readonly extraProperties?: {
    [key: string]: unknown;
  } | null;
  id?: string;
  name?: string | null;
  isDefault?: boolean;
  isStatic?: boolean;
  isPublic?: boolean;
  concurrencyStamp?: string | null;
};

export type IdentityRoleDtoListResultDto = {
  items?: Array<IdentityRoleDto> | null;
};

export type IdentityRoleDtoPagedResultDto = {
  items?: Array<IdentityRoleDto> | null;
  totalCount?: number;
};

export type IdentityRoleUpdateDto = {
  readonly extraProperties?: {
    [key: string]: unknown;
  } | null;
  name: string;
  isDefault?: boolean;
  isPublic?: boolean;
  concurrencyStamp?: string | null;
};

export type IdentityUserCreateDto = {
  readonly extraProperties?: {
    [key: string]: unknown;
  } | null;
  userName: string;
  name?: string | null;
  surname?: string | null;
  email: string;
  phoneNumber?: string | null;
  isActive?: boolean;
  lockoutEnabled?: boolean;
  roleNames?: Array<string> | null;
  password: string;
};

export type IdentityUserDto = {
  readonly extraProperties?: {
    [key: string]: unknown;
  } | null;
  id?: string;
  creationTime?: string;
  creatorId?: string | null;
  lastModificationTime?: string | null;
  lastModifierId?: string | null;
  isDeleted?: boolean;
  deleterId?: string | null;
  deletionTime?: string | null;
  tenantId?: string | null;
  userName?: string | null;
  name?: string | null;
  surname?: string | null;
  email?: string | null;
  emailConfirmed?: boolean;
  phoneNumber?: string | null;
  phoneNumberConfirmed?: boolean;
  isActive?: boolean;
  lockoutEnabled?: boolean;
  accessFailedCount?: number;
  lockoutEnd?: string | null;
  concurrencyStamp?: string | null;
  entityVersion?: number;
  lastPasswordChangeTime?: string | null;
};

export type IdentityUserDtoPagedResultDto = {
  items?: Array<IdentityUserDto> | null;
  totalCount?: number;
};

export type IdentityUserUpdateDto = {
  readonly extraProperties?: {
    [key: string]: unknown;
  } | null;
  userName: string;
  name?: string | null;
  surname?: string | null;
  email: string;
  phoneNumber?: string | null;
  isActive?: boolean;
  lockoutEnabled?: boolean;
  roleNames?: Array<string> | null;
  password?: string | null;
  concurrencyStamp?: string | null;
};

export type IdentityUserUpdateRolesDto = {
  roleNames: Array<string>;
};

export type InterfaceMethodApiDescriptionModel = {
  name?: string | null;
  parametersOnMethod?: Array<MethodParameterApiDescriptionModel> | null;
  returnValue?: ReturnValueApiDescriptionModel;
};

export type IStringValueType = {
  readonly name?: string | null;
  readonly properties?: {
    [key: string]: unknown;
  } | null;
  validator?: IValueValidator;
};

export type IValueValidator = {
  readonly name?: string | null;
  readonly properties?: {
    [key: string]: unknown;
  } | null;
};

export type LanguageInfo = {
  cultureName?: string | null;
  uiCultureName?: string | null;
  displayName?: string | null;
  readonly twoLetterISOLanguageName?: string | null;
};

export type LocalizableStringDto = {
  name?: string | null;
  resource?: string | null;
};

export type LoginResultType = 1 | 2 | 3 | 4 | 5;

export type MethodParameterApiDescriptionModel = {
  name?: string | null;
  typeAsString?: string | null;
  type?: string | null;
  typeSimple?: string | null;
  isOptional?: boolean;
  defaultValue?: unknown;
};

export type ModuleApiDescriptionModel = {
  rootPath?: string | null;
  remoteServiceName?: string | null;
  controllers?: {
    [key: string]: ControllerApiDescriptionModel;
  } | null;
};

export type ModuleExtensionDto = {
  entities?: {
    [key: string]: EntityExtensionDto;
  } | null;
  configuration?: {
    [key: string]: unknown;
  } | null;
};

export type MultiTenancyInfoDto = {
  isEnabled?: boolean;
};

export type NameValue = {
  name?: string | null;
  value?: string | null;
};

export type ObjectExtensionsDto = {
  modules?: {
    [key: string]: ModuleExtensionDto;
  } | null;
  enums?: {
    [key: string]: ExtensionEnumDto;
  } | null;
};

export type ParameterApiDescriptionModel = {
  nameOnMethod?: string | null;
  name?: string | null;
  jsonName?: string | null;
  type?: string | null;
  typeSimple?: string | null;
  isOptional?: boolean;
  defaultValue?: unknown;
  constraintTypes?: Array<string> | null;
  bindingSourceId?: string | null;
  descriptorName?: string | null;
};

export type PermissionGrantInfoDto = {
  name?: string | null;
  displayName?: string | null;
  parentName?: string | null;
  isGranted?: boolean;
  allowedProviders?: Array<string> | null;
  grantedProviders?: Array<ProviderInfoDto> | null;
};

export type PermissionGroupDto = {
  name?: string | null;
  displayName?: string | null;
  displayNameKey?: string | null;
  displayNameResource?: string | null;
  permissions?: Array<PermissionGrantInfoDto> | null;
};

export type ProfileDto = {
  readonly extraProperties?: {
    [key: string]: unknown;
  } | null;
  userName?: string | null;
  email?: string | null;
  name?: string | null;
  surname?: string | null;
  phoneNumber?: string | null;
  isExternal?: boolean;
  hasPassword?: boolean;
  concurrencyStamp?: string | null;
};

export type PropertyApiDescriptionModel = {
  name?: string | null;
  jsonName?: string | null;
  type?: string | null;
  typeSimple?: string | null;
  isRequired?: boolean;
  minLength?: number | null;
  maxLength?: number | null;
  minimum?: string | null;
  maximum?: string | null;
  regex?: string | null;
};

export type ProviderInfoDto = {
  providerName?: string | null;
  providerKey?: string | null;
};

export type RegisterDto = {
  readonly extraProperties?: {
    [key: string]: unknown;
  } | null;
  userName: string;
  emailAddress: string;
  password: string;
  appName: string;
};

export type RemoteServiceErrorInfo = {
  code?: string | null;
  message?: string | null;
  details?: string | null;
  data?: {
    [key: string]: unknown;
  } | null;
  validationErrors?: Array<RemoteServiceValidationErrorInfo> | null;
};

export type RemoteServiceErrorResponse = {
  error?: RemoteServiceErrorInfo;
};

export type RemoteServiceValidationErrorInfo = {
  message?: string | null;
  members?: Array<string> | null;
};

export type ResetPasswordDto = {
  userId?: string;
  resetToken: string;
  password: string;
};

export type ReturnValueApiDescriptionModel = {
  type?: string | null;
  typeSimple?: string | null;
};

export type SendPasswordResetCodeDto = {
  email: string;
  appName: string;
  returnUrl?: string | null;
  returnUrlHash?: string | null;
};

export type SendTestEmailInput = {
  senderEmailAddress: string;
  targetEmailAddress: string;
  subject: string;
  body?: string | null;
};

export type TenantCreateDto = {
  readonly extraProperties?: {
    [key: string]: unknown;
  } | null;
  name: string;
  adminEmailAddress: string;
  adminPassword: string;
};

export type TenantDto = {
  readonly extraProperties?: {
    [key: string]: unknown;
  } | null;
  id?: string;
  name?: string | null;
  concurrencyStamp?: string | null;
};

export type TenantDtoPagedResultDto = {
  items?: Array<TenantDto> | null;
  totalCount?: number;
};

export type TenantUpdateDto = {
  readonly extraProperties?: {
    [key: string]: unknown;
  } | null;
  name: string;
  concurrencyStamp?: string | null;
};

export type TimeZone = {
  iana?: IanaTimeZone;
  windows?: WindowsTimeZone;
};

export type TimingDto = {
  timeZone?: TimeZone;
};

export type TypeApiDescriptionModel = {
  baseType?: string | null;
  isEnum?: boolean;
  enumNames?: Array<string> | null;
  enumValues?: Array<unknown> | null;
  genericArguments?: Array<string> | null;
  properties?: Array<PropertyApiDescriptionModel> | null;
};

export type UpdateEmailSettingsDto = {
  smtpHost?: string | null;
  smtpPort?: number;
  smtpUserName?: string | null;
  smtpPassword?: string | null;
  smtpDomain?: string | null;
  smtpEnableSsl?: boolean;
  smtpUseDefaultCredentials?: boolean;
  defaultFromAddress: string;
  defaultFromDisplayName: string;
};

export type UpdateFeatureDto = {
  name?: string | null;
  value?: string | null;
};

export type UpdateFeaturesDto = {
  features?: Array<UpdateFeatureDto> | null;
};

export type UpdatePermissionDto = {
  name?: string | null;
  isGranted?: boolean;
};

export type UpdatePermissionsDto = {
  permissions?: Array<UpdatePermissionDto> | null;
};

export type UpdateProfileDto = {
  readonly extraProperties?: {
    [key: string]: unknown;
  } | null;
  userName?: string | null;
  email?: string | null;
  name?: string | null;
  surname?: string | null;
  phoneNumber?: string | null;
  concurrencyStamp?: string | null;
};

export type UserData = {
  id?: string;
  tenantId?: string | null;
  userName?: string | null;
  name?: string | null;
  surname?: string | null;
  isActive?: boolean;
  email?: string | null;
  emailConfirmed?: boolean;
  phoneNumber?: string | null;
  phoneNumberConfirmed?: boolean;
  readonly extraProperties?: {
    [key: string]: unknown;
  } | null;
};

export type UserDataListResultDto = {
  items?: Array<UserData> | null;
};

export type UserLoginInfo = {
  userNameOrEmailAddress: string;
  password: string;
  rememberMe?: boolean;
};

export type VerifyPasswordResetTokenInput = {
  userId?: string;
  resetToken: string;
};

export type WindowsTimeZone = {
  timeZoneId?: string | null;
};

export type GetApiAbpApiDefinitionData = {
  query?: {
    IncludeTypes?: boolean;
  };
};

export type GetApiAbpApiDefinitionResponse = ApplicationApiDescriptionModel;

export type GetApiAbpApiDefinitionError = RemoteServiceErrorResponse;

export type GetApiAbpApplicationConfigurationData = {
  query?: {
    IncludeLocalizationResources?: boolean;
  };
};

export type GetApiAbpApplicationConfigurationResponse =
  ApplicationConfigurationDto;

export type GetApiAbpApplicationConfigurationError = RemoteServiceErrorResponse;

export type GetApiAbpApplicationLocalizationData = {
  query: {
    CultureName: string;
    OnlyDynamics?: boolean;
  };
};

export type GetApiAbpApplicationLocalizationResponse =
  ApplicationLocalizationDto;

export type GetApiAbpApplicationLocalizationError = RemoteServiceErrorResponse;

export type GetApiAbpMultiTenancyTenantsByNameByNameData = {
  path: {
    name: string;
  };
};

export type GetApiAbpMultiTenancyTenantsByNameByNameResponse =
  FindTenantResultDto;

export type GetApiAbpMultiTenancyTenantsByNameByNameError =
  RemoteServiceErrorResponse;

export type GetApiAbpMultiTenancyTenantsByIdByIdData = {
  path: {
    id: string;
  };
};

export type GetApiAbpMultiTenancyTenantsByIdByIdResponse = FindTenantResultDto;

export type GetApiAbpMultiTenancyTenantsByIdByIdError =
  RemoteServiceErrorResponse;

export type PostApiAccountRegisterData = {
  body?: RegisterDto;
};

export type PostApiAccountRegisterResponse = IdentityUserDto;

export type PostApiAccountRegisterError = RemoteServiceErrorResponse;

export type PostApiAccountSendPasswordResetCodeData = {
  body?: SendPasswordResetCodeDto;
};

export type PostApiAccountSendPasswordResetCodeResponse = unknown;

export type PostApiAccountSendPasswordResetCodeError =
  RemoteServiceErrorResponse;

export type PostApiAccountVerifyPasswordResetTokenData = {
  body?: VerifyPasswordResetTokenInput;
};

export type PostApiAccountVerifyPasswordResetTokenResponse = boolean;

export type PostApiAccountVerifyPasswordResetTokenError =
  RemoteServiceErrorResponse;

export type PostApiAccountResetPasswordData = {
  body?: ResetPasswordDto;
};

export type PostApiAccountResetPasswordResponse = unknown;

export type PostApiAccountResetPasswordError = RemoteServiceErrorResponse;

export type GetApiAppBookByIdData = {
  path: {
    id: string;
  };
};

export type GetApiAppBookByIdResponse = BookDto;

export type GetApiAppBookByIdError = RemoteServiceErrorResponse;

export type PutApiAppBookByIdData = {
  body?: CreateUpdateBookDto;
  path: {
    id: string;
  };
};

export type PutApiAppBookByIdResponse = BookDto;

export type PutApiAppBookByIdError = RemoteServiceErrorResponse;

export type DeleteApiAppBookByIdData = {
  path: {
    id: string;
  };
};

export type DeleteApiAppBookByIdResponse = unknown;

export type DeleteApiAppBookByIdError = RemoteServiceErrorResponse;

export type GetApiAppBookData = {
  query?: {
    MaxResultCount?: number;
    SkipCount?: number;
    Sorting?: string;
  };
};

export type GetApiAppBookResponse = BookDtoPagedResultDto;

export type GetApiAppBookError = RemoteServiceErrorResponse;

export type PostApiAppBookData = {
  body?: CreateUpdateBookDto;
};

export type PostApiAppBookResponse = BookDto;

export type PostApiAppBookError = RemoteServiceErrorResponse;

export type PostApiAccountDynamicClaimsRefreshResponse = unknown;

export type PostApiAccountDynamicClaimsRefreshError =
  RemoteServiceErrorResponse;

export type GetApiSettingManagementEmailingResponse = EmailSettingsDto;

export type GetApiSettingManagementEmailingError = RemoteServiceErrorResponse;

export type PostApiSettingManagementEmailingData = {
  body?: UpdateEmailSettingsDto;
};

export type PostApiSettingManagementEmailingResponse = unknown;

export type PostApiSettingManagementEmailingError = RemoteServiceErrorResponse;

export type PostApiSettingManagementEmailingSendTestEmailData = {
  body?: SendTestEmailInput;
};

export type PostApiSettingManagementEmailingSendTestEmailResponse = unknown;

export type PostApiSettingManagementEmailingSendTestEmailError =
  RemoteServiceErrorResponse;

export type GetApiFeatureManagementFeaturesData = {
  query?: {
    providerKey?: string;
    providerName?: string;
  };
};

export type GetApiFeatureManagementFeaturesResponse = GetFeatureListResultDto;

export type GetApiFeatureManagementFeaturesError = RemoteServiceErrorResponse;

export type PutApiFeatureManagementFeaturesData = {
  body?: UpdateFeaturesDto;
  query?: {
    providerKey?: string;
    providerName?: string;
  };
};

export type PutApiFeatureManagementFeaturesResponse = unknown;

export type PutApiFeatureManagementFeaturesError = RemoteServiceErrorResponse;

export type DeleteApiFeatureManagementFeaturesData = {
  query?: {
    providerKey?: string;
    providerName?: string;
  };
};

export type DeleteApiFeatureManagementFeaturesResponse = unknown;

export type DeleteApiFeatureManagementFeaturesError =
  RemoteServiceErrorResponse;

export type PostApiAccountLoginData = {
  body?: UserLoginInfo;
};

export type PostApiAccountLoginResponse = AbpLoginResult;

export type PostApiAccountLoginError = RemoteServiceErrorResponse;

export type GetApiAccountLogoutResponse = unknown;

export type GetApiAccountLogoutError = RemoteServiceErrorResponse;

export type PostApiAccountCheckPasswordData = {
  body?: UserLoginInfo;
};

export type PostApiAccountCheckPasswordResponse = AbpLoginResult;

export type PostApiAccountCheckPasswordError = RemoteServiceErrorResponse;

export type GetApiPermissionManagementPermissionsData = {
  query?: {
    providerKey?: string;
    providerName?: string;
  };
};

export type GetApiPermissionManagementPermissionsResponse =
  GetPermissionListResultDto;

export type GetApiPermissionManagementPermissionsError =
  RemoteServiceErrorResponse;

export type PutApiPermissionManagementPermissionsData = {
  body?: UpdatePermissionsDto;
  query?: {
    providerKey?: string;
    providerName?: string;
  };
};

export type PutApiPermissionManagementPermissionsResponse = unknown;

export type PutApiPermissionManagementPermissionsError =
  RemoteServiceErrorResponse;

export type GetApiAccountMyProfileResponse = ProfileDto;

export type GetApiAccountMyProfileError = RemoteServiceErrorResponse;

export type PutApiAccountMyProfileData = {
  body?: UpdateProfileDto;
};

export type PutApiAccountMyProfileResponse = ProfileDto;

export type PutApiAccountMyProfileError = RemoteServiceErrorResponse;

export type PostApiAccountMyProfileChangePasswordData = {
  body?: ChangePasswordInput;
};

export type PostApiAccountMyProfileChangePasswordResponse = unknown;

export type PostApiAccountMyProfileChangePasswordError =
  RemoteServiceErrorResponse;

export type GetApiIdentityRolesAllResponse = IdentityRoleDtoListResultDto;

export type GetApiIdentityRolesAllError = RemoteServiceErrorResponse;

export type GetApiIdentityRolesData = {
  query?: {
    ExtraProperties?: {
      [key: string]: unknown;
    };
    Filter?: string;
    MaxResultCount?: number;
    SkipCount?: number;
    Sorting?: string;
  };
};

export type GetApiIdentityRolesResponse = IdentityRoleDtoPagedResultDto;

export type GetApiIdentityRolesError = RemoteServiceErrorResponse;

export type PostApiIdentityRolesData = {
  body?: IdentityRoleCreateDto;
};

export type PostApiIdentityRolesResponse = IdentityRoleDto;

export type PostApiIdentityRolesError = RemoteServiceErrorResponse;

export type GetApiIdentityRolesByIdData = {
  path: {
    id: string;
  };
};

export type GetApiIdentityRolesByIdResponse = IdentityRoleDto;

export type GetApiIdentityRolesByIdError = RemoteServiceErrorResponse;

export type PutApiIdentityRolesByIdData = {
  body?: IdentityRoleUpdateDto;
  path: {
    id: string;
  };
};

export type PutApiIdentityRolesByIdResponse = IdentityRoleDto;

export type PutApiIdentityRolesByIdError = RemoteServiceErrorResponse;

export type DeleteApiIdentityRolesByIdData = {
  path: {
    id: string;
  };
};

export type DeleteApiIdentityRolesByIdResponse = unknown;

export type DeleteApiIdentityRolesByIdError = RemoteServiceErrorResponse;

export type GetApiMultiTenancyTenantsByIdData = {
  path: {
    id: string;
  };
};

export type GetApiMultiTenancyTenantsByIdResponse = TenantDto;

export type GetApiMultiTenancyTenantsByIdError = RemoteServiceErrorResponse;

export type PutApiMultiTenancyTenantsByIdData = {
  body?: TenantUpdateDto;
  path: {
    id: string;
  };
};

export type PutApiMultiTenancyTenantsByIdResponse = TenantDto;

export type PutApiMultiTenancyTenantsByIdError = RemoteServiceErrorResponse;

export type DeleteApiMultiTenancyTenantsByIdData = {
  path: {
    id: string;
  };
};

export type DeleteApiMultiTenancyTenantsByIdResponse = unknown;

export type DeleteApiMultiTenancyTenantsByIdError = RemoteServiceErrorResponse;

export type GetApiMultiTenancyTenantsData = {
  query?: {
    Filter?: string;
    MaxResultCount?: number;
    SkipCount?: number;
    Sorting?: string;
  };
};

export type GetApiMultiTenancyTenantsResponse = TenantDtoPagedResultDto;

export type GetApiMultiTenancyTenantsError = RemoteServiceErrorResponse;

export type PostApiMultiTenancyTenantsData = {
  body?: TenantCreateDto;
};

export type PostApiMultiTenancyTenantsResponse = TenantDto;

export type PostApiMultiTenancyTenantsError = RemoteServiceErrorResponse;

export type GetApiMultiTenancyTenantsByIdDefaultConnectionStringData = {
  path: {
    id: string;
  };
};

export type GetApiMultiTenancyTenantsByIdDefaultConnectionStringResponse =
  string;

export type GetApiMultiTenancyTenantsByIdDefaultConnectionStringError =
  RemoteServiceErrorResponse;

export type PutApiMultiTenancyTenantsByIdDefaultConnectionStringData = {
  path: {
    id: string;
  };
  query?: {
    defaultConnectionString?: string;
  };
};

export type PutApiMultiTenancyTenantsByIdDefaultConnectionStringResponse =
  unknown;

export type PutApiMultiTenancyTenantsByIdDefaultConnectionStringError =
  RemoteServiceErrorResponse;

export type DeleteApiMultiTenancyTenantsByIdDefaultConnectionStringData = {
  path: {
    id: string;
  };
};

export type DeleteApiMultiTenancyTenantsByIdDefaultConnectionStringResponse =
  unknown;

export type DeleteApiMultiTenancyTenantsByIdDefaultConnectionStringError =
  RemoteServiceErrorResponse;

export type GetApiSettingManagementTimezoneResponse = string;

export type GetApiSettingManagementTimezoneError = RemoteServiceErrorResponse;

export type PostApiSettingManagementTimezoneData = {
  query?: {
    timezone?: string;
  };
};

export type PostApiSettingManagementTimezoneResponse = unknown;

export type PostApiSettingManagementTimezoneError = RemoteServiceErrorResponse;

export type GetApiSettingManagementTimezoneTimezonesResponse = Array<NameValue>;

export type GetApiSettingManagementTimezoneTimezonesError =
  RemoteServiceErrorResponse;

export type GetApiIdentityUsersByIdData = {
  path: {
    id: string;
  };
};

export type GetApiIdentityUsersByIdResponse = IdentityUserDto;

export type GetApiIdentityUsersByIdError = RemoteServiceErrorResponse;

export type PutApiIdentityUsersByIdData = {
  body?: IdentityUserUpdateDto;
  path: {
    id: string;
  };
};

export type PutApiIdentityUsersByIdResponse = IdentityUserDto;

export type PutApiIdentityUsersByIdError = RemoteServiceErrorResponse;

export type DeleteApiIdentityUsersByIdData = {
  path: {
    id: string;
  };
};

export type DeleteApiIdentityUsersByIdResponse = unknown;

export type DeleteApiIdentityUsersByIdError = RemoteServiceErrorResponse;

export type GetApiIdentityUsersData = {
  query?: {
    ExtraProperties?: {
      [key: string]: unknown;
    };
    Filter?: string;
    MaxResultCount?: number;
    SkipCount?: number;
    Sorting?: string;
  };
};

export type GetApiIdentityUsersResponse = IdentityUserDtoPagedResultDto;

export type GetApiIdentityUsersError = RemoteServiceErrorResponse;

export type PostApiIdentityUsersData = {
  body?: IdentityUserCreateDto;
};

export type PostApiIdentityUsersResponse = IdentityUserDto;

export type PostApiIdentityUsersError = RemoteServiceErrorResponse;

export type GetApiIdentityUsersByIdRolesData = {
  path: {
    id: string;
  };
};

export type GetApiIdentityUsersByIdRolesResponse = IdentityRoleDtoListResultDto;

export type GetApiIdentityUsersByIdRolesError = RemoteServiceErrorResponse;

export type PutApiIdentityUsersByIdRolesData = {
  body?: IdentityUserUpdateRolesDto;
  path: {
    id: string;
  };
};

export type PutApiIdentityUsersByIdRolesResponse = unknown;

export type PutApiIdentityUsersByIdRolesError = RemoteServiceErrorResponse;

export type GetApiIdentityUsersAssignableRolesResponse =
  IdentityRoleDtoListResultDto;

export type GetApiIdentityUsersAssignableRolesError =
  RemoteServiceErrorResponse;

export type GetApiIdentityUsersByUsernameByUserNameData = {
  path: {
    userName: string;
  };
};

export type GetApiIdentityUsersByUsernameByUserNameResponse = IdentityUserDto;

export type GetApiIdentityUsersByUsernameByUserNameError =
  RemoteServiceErrorResponse;

export type GetApiIdentityUsersByEmailByEmailData = {
  path: {
    email: string;
  };
};

export type GetApiIdentityUsersByEmailByEmailResponse = IdentityUserDto;

export type GetApiIdentityUsersByEmailByEmailError = RemoteServiceErrorResponse;

export type GetApiIdentityUsersLookupByIdData = {
  path: {
    id: string;
  };
};

export type GetApiIdentityUsersLookupByIdResponse = UserData;

export type GetApiIdentityUsersLookupByIdError = RemoteServiceErrorResponse;

export type GetApiIdentityUsersLookupByUsernameByUserNameData = {
  path: {
    userName: string;
  };
};

export type GetApiIdentityUsersLookupByUsernameByUserNameResponse = UserData;

export type GetApiIdentityUsersLookupByUsernameByUserNameError =
  RemoteServiceErrorResponse;

export type GetApiIdentityUsersLookupSearchData = {
  query?: {
    ExtraProperties?: {
      [key: string]: unknown;
    };
    Filter?: string;
    MaxResultCount?: number;
    SkipCount?: number;
    Sorting?: string;
  };
};

export type GetApiIdentityUsersLookupSearchResponse = UserDataListResultDto;

export type GetApiIdentityUsersLookupSearchError = RemoteServiceErrorResponse;

export type GetApiIdentityUsersLookupCountData = {
  query?: {
    Filter?: string;
  };
};

export type GetApiIdentityUsersLookupCountResponse = number;

export type GetApiIdentityUsersLookupCountError = RemoteServiceErrorResponse;
